version: "3.7"
services:
  frontend:
    build: .
    image: arghya1988/to-do-list-app
    ports: 
      - "8880:80"
    networks:
      - default-network
networks:
  default-network: 
    driver: bridge
